DEEPSEEK_API_KEY = "sk-b3942b26e41c47789cdc8a7544393e93"
SUPABASE_URL = "https://sgvnovxzltutzkadrmxb.supabase.co"
SUPABASE_KEY = "sb_publishable_QGUt-w-3HAz-y5fGBdMKCA_b37CZEIi"
TIKHUB_API_KEY = "你的TikHub API Key"
